# -*- coding: utf-8 -*-
"""res1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MQGFGGm_tcxg2v29j6GJ8CtZdvyXYrJx
"""

import pandas as pd

# case1_구글크롤링 전체 NaN 행 삭제
essential_cols_case1 = ['구글가게명', '구글주소', '별점', '카테고리', '리뷰수', '구글위도', '구글경도']
df = df.dropna(subset=essential_cols_case1, how='all')

# case2_리뷰수, 별점,카테고리 모두 NaN 행 삭제
essential_cols_case2 = ['리뷰수', '별점', '카테고리']

# 문자열 "None"을 NaN으로 변환
df[essential_cols_case2] = df[essential_cols_case2].replace("none", pd.NA)
df = df.dropna(subset=essential_cols_case2, how='all')

# case3_리뷰수, 별점, 모두 NaN 행 삭제
essential_cols_case3 = ['리뷰수', '별점']

# 문자열 "None"을 NaN으로 변환
df[essential_cols_case3] = df[essential_cols_case3].replace("none", pd.NA)
df = df.dropna(subset=essential_cols_case3, how='all')

# 리뷰수 숫자로 변환하고, 음수 → 양수 → 정수
df['리뷰수'] = pd.to_numeric(df['리뷰수'], errors='coerce')
df['리뷰수'] = df['리뷰수'].abs().astype('Int64')

df['별점'] = pd.to_numeric(df['별점'], errors='coerce')

# 리뷰수 결측 삭제 + 인덱스 초기화
df = df.dropna(subset=['리뷰수']).reset_index(drop=True)
